### PR TITLE
Improve SEO Rankings

### PR DESCRIPTION
**Pull request by Blake-Haydon**
## Description

This PR does a couple of best practices that should help with SEO. 

- Site maps were supplied to Bing and Google
- Added Yandex verification
- Adds titles that are better for search
- Adds the option to change the description of a page in the CMS
 

### SEO description added to CMS (will default to the global of nothing has been put down)
image

### Full title for all pages (Changed from MHP)
Screen Shot 2020-10-26 at 10 40 11 pm

_index page_

Screen Shot 2020-10-26 at 10 42 25 pm

_bikes page_

## Steps to Test

Check out the PR link or run `gatsby develop` locally

### CODE REVIEW

**Review by hallgchris — COMMENTED** [review]
Looks good to me overall! A couple quick questions.

- Should we have the default page description settable in CMS? Or do you believe this isn't worth it as all pages should be overriding this anyway. (The current default one isn't really great)
  - If you think it'll always be overridden, should we make it a required field and get rid of the default altogether?
- What changes did you make for the site map in this PR, if any?

**Review by harsilspatel — APPROVED** [review]
Looks good to me! :shipit: 

P.S: I searched _Monash human power_ (in incognito) on a couple of devices using different browsers and the website shows up at 4th place on the 1st page!

**Comment by harsilspatel** [comment]
@hallgchris 
That's a good question, I reckon Blake may have submitted the sitemap directly (if that's a thing lol) but regardless the previous changes definitely brought up the site rankings and hopefully this gets it even higher!

**Comment by hallgchris** [comment]
> regardless the previous changes definitely brought up the site rankings

Wow we've shot up since I last checked! Nice work Blake!

**Comment by Blake-Haydon** [comment]
The site map gets automatically uploaded so we don't need to stress about re uploading it every time.

**Pull request merged**
