### PR TITLE
Update dependencies (gatsby, bootstrap etc)

### PR DESCRIPTION
**Pull request by megascrapper**
## Description

Our site currently runs old and deprecated [versions of gatsby](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) and [bootstrap](https://endoflife.date/bootstrap) which might cause issues down the line if we didn't fix it now. So I updated them all to the latest major version along with its plugins and other packages.

Also replaced `gatsby-image` with `gatsby-plugin-image` since the former has been deprecated

## Screenshots

image

## Steps to Test

Deploy as normal. 

Please let me know if there's something that's broken since there's quite a lot of manual intervention I need to do during the migration.

### CODE REVIEW

**Comment by megascrapper** [comment]
@kdav108 looks like you need to set node version to 18 or later in Netlify as per [Gatsby docs](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/#minimal-nodejs-version-1800). The site builds in my local machine with node v19.1.0

**Comment by kdav108** [comment]
> @kdav108 looks like you need to set node version to 18 or later in Netlify as per [Gatsby docs](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/#minimal-nodejs-version-1800). The site builds in my local machine with node v19.1.0

I think it's a good idea upgrading to a newer Node version; there are 2 ways we can do this, refer [here](https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript), I would say let's go with option 2, creating a `.node-version` file so we can easily change and verify what node version we're using without having access to Netlify.

`.node-version` should be a [pretty simple file](https://render.com/docs/node-version) with just the version name written in it. Then the Netlify build should automatically pick up that version for the website.

CC @AroshHeenkenda

**Comment by megascrapper** [comment]
Looks like someone has to clear the build cache to force it to use the latest version.

<https://answers.netlify.com/t/node-version-caching/10014>

From the build log:

```
...
10:50:09 AM: Started restoring cached node version
10:50:10 AM: Finished restoring cached node version
10:50:10 AM: v12.18.0 is already installed.
10:50:11 AM: Now using node v12.18.0 (npm v6.14.4)
...
```

**Comment by kdav108** [comment]
Tried to clear cache and redeploy but it still wasn't picking node 18, perhaps the node-version file needs to state 18.0.0 or similar version?

**Comment by megascrapper** [comment]
Looks like the problem is a typo: `.node-version` should be in dashes and not underscores.

**Pull request merged**
